### ISSUE TITLE
Firefox changes event names for gamepad API (no prefix, all lowercase)

### ISSUE THREAD

**Issue by dertseha** [kallaspriit/HTML5-JavaScript-Gamepad-Controller-Library#10]
The naming guidelines for events got enforced and they will be all without prefix and lowercase (in the next Aurora build that supports Gamepad API again):
https://bugzilla.mozilla.org/show_bug.cgi?id=604039#c206

The attached test page to this bug also uses these new names.

**Comment by mildmojo** [comment]
Looks like this can be closed now?

**Comment by dertseha** [comment]
Yes, thanks for the heads-up.
