### ISSUE TITLE
Contribution guidelines & scripts?

### ISSUE THREAD

**Issue by dertseha** [kallaspriit/HTML5-JavaScript-Gamepad-Controller-Library#11]
I have a few ideas to enhance the library, and instead of rolling my own (and yet another), I'd like to contribute here.

But before I do that, I'd like to ask for some guidelines, specifically .jshintrc and .jsbeautifyrc files.
Furthermore I'd like to have the build scripts as part of the repository as well; I don't know what you are using, but I'd be happy to add a grunt based setup.

**Comment by kallaspriit** [comment]
Contributions are certainly welcome, I will add a .jshintrc file. As it's a single file, I haven't been using a full-blown build system but I guess a simple one wouldn't hurt.

**Comment by dertseha** [comment]
Please also add the .jsbeautifyrc file. When my save-auto-format changes various stuff, I want to have it in the same style as expected :) (Read: I don't care what type of indentation or bracket style is used, I just want to have the same one ensured by the machine)

**Comment by kallaspriit** [comment]
I haven't really used the .jsbeautifyrc before, I guess you could propose your own that would leave the current style more or less the same or let me know if you think some things should be formatted differently in your opinion. I might try to find time to figure this out myself too though I have to check if my Webstorm IDE supports this anyway.

**Comment by kallaspriit** [comment]
I commented the code using yuidoc conventions and added documentation pages.

**Comment by dertseha** [comment]
Thanks for accepting!
