### ISSUE TITLE
Standardize button names reported by library

### ISSUE THREAD

**Issue by dertseha** [kallaspriit/HTML5-JavaScript-Gamepad-Controller-Library#12]
As a user of the library, I don't want to be concerned what kind of gamepad is connected; I don't care whether the button is called "A" or "SQUARE" for instance.

While the [spec](https://dvcs.w3.org/hg/gamepad/raw-file/default/gamepad.html) does not specify the names, the [HTML5Rocks page](http://www.html5rocks.com/en/tutorials/doodles/gamepad/) has a nice [image](http://1-ps.googleusercontent.com/x/s.html5rocks-hrd.appspot.com/www.html5rocks.com/en/tutorials/doodles/gamepad/xgamepad_diagram.png.pagespeed.ic.xgYXkWxzYh.webp) showcasing example names.

Any device specific names could then be layered over them should a UI need them. But the technical names should be unified.

**Comment by kallaspriit** [comment]
I agree with the idea, is this something you would like to implement?

**Comment by dertseha** [comment]
Sure, although I'm focusing on first things first - getting the basic project structure running ;)

**Comment by dertseha** [comment]
I have started to work on the standardization of the button names and as a cross-check, I tried to test the two gamepads that I have (the older Logitech one and a PS3 controller) where possible.
So far I couldn't do too much, because under Win7, the PS3 controller is not supported and the MotionJoy driver doesn't seem to be compatible with the browser. (And I have to find the download-link again for Aurora build 17)

But on Mac & Chrome, both were registered. While the PS3 controller is the same as on Linux, the Logitech one is handled different. While on Linux the DPAD is handled as two further axes, under Mac they are 4 buttons.

What OS were you testing on? I get the feeling that the layout of buttons and axes is not only browser, but also OS dependent, which might become tricky if we wanted to standardize across all device/browser/OS combos.

The alternative idea I am playing with is to standardize not the button names, but the interface how buttons and axes are reported: In my app that I want to use the gamepad I needed to split the axis events into two: a positive and a negative control - i.e. for one X axis in one that mapped to "turn left" and the other to "turn right". I did this to allow the bindings for the same actions to be to buttons as well.
It comes down to have only generic "controls" that have a value range of [0..1](negative ones are made absolute).

With this lower-level access and especially the mixup with various combinations there won't be a chance to standardize on button names (i.e. "dpad") but simply "control_xx". Only a higher-leverl mapping could try to give abstract names (like "start" or "dpad") to them again.

Either way, this would be a quite different approach to the Gamepad-API and I'm not sure whether this is still within the vision of your library. Although, it could be a dedicated event for the abstract controls and the button/axis events are the higher-level API - with best-effort mapping.

What do you think?

**Comment by kallaspriit** [comment]
I'm on Windows and it would really suck if it was also OS dependent, can't check this myself. I don't see much point in splitting the axes events as this is something easily done on the application side. I'm not sure how much of the controls can be unified but the main buttons should be doable.

**Comment by dertseha** [comment]
Thank you for accepting the pull request!
