### ISSUE TITLE
controller connects twice if connected with both bluetooth and wire

### ISSUE THREAD

**Issue by JakeChampion** [kallaspriit/HTML5-JavaScript-Gamepad-Controller-Library#6]
Software used:
Chrome
Hardware used:
PS3 controller and charging cable

When PS3 controller is connected to the computer via both wire and bluetooth, browser will connect the same controller up twice but only report events for the newest gamepad connection.

This is a problem when playing a one player game as the code for the game wont ever reference a second gamepad and the only way to resolve this is to disconnect one of the connections and then restart the browser.

**Comment by kallaspriit** [comment]
Not sure if this can be handled in the library, what do you suggest?

**Comment by JakeChampion** [comment]
I'll first test this in WebKit, gecko and trident to see if its browser
specific. The main issue is that the controller that handles the input is
controller 2, so if the game is made with only one gamepad in mind then the
inputs won't get handled. I would think that detecting the unique ids and
checking if they're the same and if so, to disconnect one.

What do you think?

**Comment by kallaspriit** [comment]
I suppose two real controllers could have the same ID?

**Comment by JakeChampion** [comment]
According to the W3 a gamepad's ID is

> An identification string for the gamepad. This string identifies the brand or style of connected gamepad device. Typically, this will include the USB vendor and a product ID.

MDN also say the gamepads properties are

> id: a unique id (string) for the gamepad.
> connected: true if the gamepad is still connected to the system.
> buttons: an array of the buttons present on the device. Each entry in the array is 0 if the button is not pressed, and non-zero (typically 1.0) if the button is pressed.
> axes: an array of the axes present on the device. Each entry in the array is a float value in the range -1.0..1.0 representing the axis position from the lowest value (-1.0) to the highest value (1.0).
> index: a unique auto-incrementing number for each gamepad connected to the system. A gamepad that is disconnected and reconnected will retain the same index.

So I don't think they can have the same ID and so it's possible to do an equality check on IDs and if they match, disconnect the gamepad which has the highest index.

**Comment by JakeChampion** [comment]
I don't think this piece of functionality should be implemented at the library level but rather at the browser vendor level. What do you think?

**Comment by dertseha** [comment]
Do you have the reported IDs ready? Can do reproduce this?
Also, on which OS is this happening? If it's on Windows, are also two dedicated controllers reported in the Joystick control panel of Windows in this case?
I do have a PS3 controller, but no bluetooth nor proper support for that under Win7, so I can't reproduce this.

**Comment by JakeChampion** [comment]
Chrome version: 28.0.1500.71  Channel: stable
OS Version: OS X 10.8.4

I don't have the IDs ready and can not reproduce this until I'm back at my desk this weekend.

I will take screenshots of the problem and report the IDs back here when I've repeated this.

**Comment by JakeChampion** [comment]
I've since moved and have no gamepads to replicate this issue, there's a bug report in chrome for this that I've made. Shall I close this as it's really a browser issue?

**Comment by kallaspriit** [comment]
Sounds reasonable :)

**Comment by JakeChampion** [comment]
[CRBUG-261216](https://code.google.com/p/chromium/issues/detail?id=261216)
